services:
  mysql:
    ports: !reset []
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --innodb-buffer-pool-size=256M
  redis:
    ports: !reset []
  backend:
    ports: !reset []
    environment:
      JAVA_TOOL_OPTIONS: -Xms256m -Xmx768m
  nginx:
    ports: !override
      - "80:80"
